# Operadores matemáticos
print('Operadores matemáticos:')
print(10 + 3)
print(10 - 3)
print(10 * 3)
print(10 / 3)
print(10 / 3.0)
print(13 / 3)
print(13 / 3.0)
print(13 // 3.0)
print(2 ** 4)
print(26 % 5)

# Ordem dos operadores
print('\nOrdem dos operadores:')
print(5 + 30 * 20)
print((5 + 30) * 20)
print(((5 + 30) * 20) / 10)
print(5 + 30 * 20 / 10)

# Operadores de comparacão
print('\nOperadores de comparacão:')
print(2 < 3)
print(9 > 8)
print(1 == 1)
print(1 != 2)
print(1 != 1)
print(4 <= 4)
print(5 >= 6)
print(1 < 2 < 3)
print(1 < 2 < 2)
print(1 + 2 < 25 / 5)

# Operadores lógicos
print('\nOperadores lógicos:')
print(not True)
print(not False)
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print(True or True and False)
print((True or True) and False)
print(not True or False)
print(not (True or False))
print(not (True and False) and (True or False))
print(1 > 2 and 3 > 4)
print(1 > 2 and 3 < 4)
print(1 < 2 and 3 < 4)
print(1 + 2 and 3 + 4)
print(1 + 2 or 3 + 4)
print( True and 3 > 5)
print(False and 3 > 5)
